In [2]:
import numpy as np
identity_matrix=np.identity(3)
print("3X3 Indentity Matrix")
print(identity_matrix)
      

3X3 Indentity Matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
import numpy as np
null_matrix=np.zeros((3,3))
print("3X3 Null Matrix")
print(null_matrix)

3X3 Null Matrix
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
one_matrix=np.ones((3,3))
print(one_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
#create a list and covert them into array
my_list=[1,2,3,4,5]
my_array=np.array(my_list)
print(my_array)

[1 2 3 4 5]


In [8]:
list1=[1,2,3,4,5,6]
list2=[5,6,7,8,9]
l3=list1+list2
array=np.array(l3)
print(array)

[1 2 3 4 5 6 5 6 7 8 9]


In [12]:
my_list=[]
for i in range(1,11):
    my_list.append(i)

print(my_list)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [13]:
my_array=np.array([])
for i in range(1,11):
    my_array=np.append(my_array,i)

print(my_array)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [14]:
my_array=np.array([])
for i in range(1,11):
    my_array=np.append(my_array,i)
my_array=my_array.astype(int)
print(my_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
list1=[]
n=int(input())
for i in range(n):
    a=input();
    list1.append(a)

print(list1)


 10
 abc
 def
 ghi
 jkl
 mno
 pqr
 stu
 vwx
 yz
 abd


['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abd']


In [17]:
#insert 10 string elements in matrix
arr=np.array([])
for i in range(0,10):
    arr=np.append(arr,input())

print(arr)


 a
 b
 c
 d
 e
 f
 g
 h
 i
 j


['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']


In [1]:
arr=np.array([])
n=int(input())
for i in range(n):
      a=int(input())
      arr=np.append(arr,a*3)



print(arr)


NameError: name 'np' is not defined